"""add_team_join_requests_table

Revision ID: ac1b8e20818d
Revises: 0001_initial_schema
Create Date: 2026-09-10 15:15:29.131271

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ac1b8e20818d"
down_revision: str | Sequence[str] | None = "0001_initial_schema"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "team_join_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("team_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("tournament_id", sa.UUID(), nullable=False),
        sa.Column("game_role", sa.String(length=50), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("responded_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'accepted', 'rejected')",
            name="check_join_request_status",
        ),
        sa.ForeignKeyConstraint(["team_id"], ["teams.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["tournament_id"], ["tournaments.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_team_join_requests_status"),
        "team_join_requests",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_team_join_requests_team_id"),
        "team_join_requests",
        ["team_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_team_join_requests_tournament_id"),
        "team_join_requests",
        ["tournament_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_team_join_requests_user_id"),
        "team_join_requests",
        ["user_id"],
        unique=False,
    )
    op.drop_index(op.f("ix_messages_team_created"), table_name="messages")
    op.create_index(
        op.f("ix_messages_author_id"), "messages", ["author_id"], unique=False
    )
    op.create_index(
        op.f("ix_messages_created_at"), "messages", ["created_at"], unique=False
    )
    op.create_index(op.f("ix_messages_team_id"), "messages", ["team_id"], unique=False)
    op.drop_constraint(op.f("uq_users_email"), "users", type_="unique")
    op.drop_constraint(op.f("uq_users_username"), "users", type_="unique")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=False)
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=False)
    op.create_unique_constraint(
        op.f("uq_users_username"),
        "users",
        ["username"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_unique_constraint(
        op.f("uq_users_email"), "users", ["email"], postgresql_nulls_not_distinct=False
    )
    op.drop_index(op.f("ix_messages_team_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_created_at"), table_name="messages")
    op.drop_index(op.f("ix_messages_author_id"), table_name="messages")
    op.create_index(
        op.f("ix_messages_team_created"),
        "messages",
        ["team_id", "created_at"],
        unique=False,
    )
    op.drop_index(
        op.f("ix_team_join_requests_user_id"), table_name="team_join_requests"
    )
    op.drop_index(
        op.f("ix_team_join_requests_tournament_id"), table_name="team_join_requests"
    )
    op.drop_index(
        op.f("ix_team_join_requests_team_id"), table_name="team_join_requests"
    )
    op.drop_index(op.f("ix_team_join_requests_status"), table_name="team_join_requests")
    op.drop_table("team_join_requests")
    # ### end Alembic commands ###
